after_success: cover -report coveralls -test
compiler: gcc
install: cpanm -nq Devel::Cover::Report::Coveralls
language: perl
matrix:
    include:
        - compiler: clang
          perl: "5.19"
        - compiler: gcc
          perl: "5.19"
        - compiler: gcc
          perl: "5.18"
        - compiler: gcc
          perl: "5.16"
        - compiler: gcc
          perl: "5.14"
        - compiler: gcc
          perl: "5.12"
script:
    - echo $CC
    - ls -l $(which cc)
    - ls -l /etc/alternatives/cc
    - sudo ln -fs $(which $(perl -e '$ENV{TRAVIS_JOB_NUMER} =~ /\.1$/ ? "clang" : "gcc"')) $(which cc)
    - perl Makefile.PL INSTALLMAN3DIR=none NO_MYMETA=1
    - make
    - prove -bl
