after_success: "[ $CC == /usr/bin/gcc ] && cover -report coveralls -test"
before_install:
    - sudo ln -fs $CC /usr/bin/cc
    - cc --version
env:
    - CC=/usr/local/bin/clang
    - CC=/usr/bin/gcc
install: "[ $CC == /usr/bin/gcc ] && cpanm -nq Devel::Cover::Report::Coveralls"
language: perl
perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"
script:
    - perl Makefile.PL INSTALLMAN3DIR=none NO_MYMETA=1
    - make
    - prove -bl
