after_success: cover -report coveralls -test
compiler: gcc
env:
    - CC=/usr/bin/clang
    - CC=/usr/bin/gcc
install: cpanm -nq Devel::Cover::Report::Coveralls
language: perl
perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
script:
    - which clang
    - ls -l /usr/bin/cc
    - sudo ln -fs $CC /usr/bin/cc
    - ls -l /usr/bin/cc
    - perl Makefile.PL INSTALLMAN3DIR=none NO_MYMETA=1
    - make
    - prove -bl
