after_success: "[ $CC = gcc ] && cover -coverage default,-pod -ignore_re '\\.h$' -report coveralls -test"
env:
    # Old stables.
    - CC=gcc   PB_OPT=perl-5.18.4
    - CC=gcc   PB_OPT=perl-5.20.3

    # Stable, with each compiler.
    - CC=clang PB_OPT=perl-5.22.1
    - CC=gcc   PB_OPT=perl-5.22.1

    # Latest.
    - CC=gcc   PB_OPT=perl-5.23.9
    - CC=gcc   PB_OPT=perl-blead

    # Stable, weird and whacky config options.
    - CC=gcc   PB_OPT='--64all  perl-5.22.1'
    - CC=gcc   PB_OPT='--64int  perl-5.22.1'
    - CC=gcc   PB_OPT='--ld     perl-5.22.1'
    - CC=gcc   PB_OPT='--multi  perl-5.22.1'
    - CC=gcc   PB_OPT='--thread perl-5.22.1'
install:
    - perlbrew install -Accflags=-DNO_MATHOMS -Dusedevel -j`nproc` -n --noman $PB_OPT
    - perlbrew use ${PB_OPT/* }
    - perl -V
    - cpanm -nq Devel::Cover::Report::Coveralls Test::Fatal
language: perl
script:
    - perl Makefile.PL CC=$CC INSTALLMAN3DIR=none NO_MYMETA=1
    - make
    - prove -bl
sudo: false
