after_success: "[ $CC == gcc ] && cover -report coveralls -test"
env:
    # Old stable.
    - CC=gcc   PB_OPT=perl-5.18.2

    # Latest stable, defaults with each compiler.
    - CC=clang PB_OPT=perl-5.20.0
    - CC=gcc   PB_OPT=perl-5.20.0

    # Test latest perl.
    - CC=gcc   PB_OPT=perl-5.21.0

    # Test weird and whacky options with stable.
    - CC=gcc   PB_OPT='--64all  perl-5.20.0'
    - CC=gcc   PB_OPT='--64int  perl-5.20.0'
    - CC=gcc   PB_OPT='--ld     perl-5.20.0'
    - CC=gcc   PB_OPT='--multi  perl-5.20.0'
    - CC=gcc   PB_OPT='--thread perl-5.20.0'
install:
    - sudo ln -fs $(which $CC) /usr/bin/cc
    - perlbrew install -DNO_MATHOMS -Dusedevel -j`nproc` -n --noman $PB_OPT
    - perlbrew use `echo $PB_OPT | awk '{print $NF}'`
    - cpanm -nq Test::Fatal
    - "if [ $CC == gcc ]; then cpanm -nq Devel::Cover::Report::Coveralls IO::Socket::SSL; fi"
language: perl
script:
    - perl Makefile.PL INSTALLMAN3DIR=none NO_MYMETA=1
    - make
    - prove -bl
