after_success: cover -report coveralls -test
install: cpanm -nq Devel::Cover::Report::Coveralls
language: perl
matrix:
    include:
        - compiler: clang
          perl: "5.19"
perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
script:
    - echo $CC
    - ls -l $(which cc)
    - perl Makefile.PL INSTALLMAN3DIR=none NO_MYMETA=1
    - make
    - prove -bl
