after_success: "[ $CC == gcc ] && cover -report coveralls -test"
env:
    - CC=clang
    - CC=gcc
install:
    - sudo ln -fs $(which $CC) /usr/bin/cc
    - "if [ $CC == gcc ]; then cpanm -nq Devel::Cover::Report::Coveralls; fi"
language: perl
perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"
script:
    - perl Makefile.PL INSTALLMAN3DIR=none NO_MYMETA=1
    - make
    - prove -bl
